export const LEVEL_THRESHOLDS = [
  { level: 1, name: 'Seedling', minCO2Tracked: 0 },
  { level: 2, name: 'Sprout', minCO2Tracked: 5 },
  { level: 3, name: 'Sapling', minCO2Tracked: 15 },
  { level: 4, name: 'Young Tree', minCO2Tracked: 30 },
  { level: 5, name: 'Rooted', minCO2Tracked: 50 },
  { level: 6, name: 'Branching Out', minCO2Tracked: 75 },
  { level: 7, name: 'Forest Guardian', minCO2Tracked: 100 },
  { level: 8, name: 'Ecosystem Builder', minCO2Tracked: 150 },
  { level: 9, name: 'Climate Warrior', minCO2Tracked: 250 },
  { level: 10, name: 'Carbon Champion', minCO2Tracked: 500 },
];

export const BADGE_DEFINITIONS = [
  {
    key: 'first_step',
    name: 'First Step',
    description: 'Log your first activity',
    icon: 'Footprints',
    thresholdType: 'total_logs',
    thresholdValue: 1,
  },
  {
    key: 'streak_7',
    name: '7-Day Streak',
    description: '7 consecutive days logged',
    icon: 'Flame',
    thresholdType: 'streak',
    thresholdValue: 7,
  },
  {
    key: 'green_commuter',
    name: 'Green Commuter',
    description: 'Log 10 transport entries',
    icon: 'Train',
    thresholdType: 'transport_logs',
    thresholdValue: 10,
  },
  {
    key: 'plant_power',
    name: 'Plant Power',
    description: 'Log 10 plant-based meals',
    icon: 'Salad',
    thresholdType: 'plant_logs',
    thresholdValue: 10,
  },
  {
    key: 'energy_saver',
    name: 'Energy Saver',
    description: 'Log 10 home energy entries',
    icon: 'Zap',
    thresholdType: 'energy_logs',
    thresholdValue: 10,
  },
  {
    key: 'carbon_crusher',
    name: 'Carbon Crusher',
    description: 'Track 100 kg CO₂ total',
    icon: 'Trophy',
    thresholdType: 'co2_tracked',
    thresholdValue: 100,
  },
];
